spring.application.name=football-club-management-api

# 1. Coordenadas de la Base de Datos (MySQL 8.0 Nativo)
spring.datasource.url=jdbc:mysql://localhost:3306/dtfutbol_core?serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración del ORM y Transacciones (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Optimización de Conexiones
spring.jpa.open-in-view=false


# 4. Formatear el SQL para que sea legible por humanos
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always